### ISSUE TITLE
Remove solr lock file on startup

### ISSUE THREAD

**Issue by ernstp** [blackducksoftware/hub#13]
When the solr docker container is starting it could 
rm -f /opt/blackduck/hub/solr/cores.data/project/index/write.lock
because it's obviously not running yet.
Otherwise you get 

> 2017-10-19 10:51:16,831 [qtp1129670968-17] ERROR org.apache.solr.servlet.HttpSolrCall - null:org.apache.solr.common.SolrException: SolrCore 'project' is not available due to init failure: Index dir '/opt/blackduck/hub/solr/cores.data/project/index/' of core 'project' is already locked. The most likely cause is another Solr server (or another solr core in this server) also configured to use this directory; other possible causes may be specific to lockType: simple

after a restart.

**Comment by robpacheco** [comment]
In Hub 4.2.0 this typically happens when Solr does not shut down cleanly - which can be for a variety of reasons. We have fixed this issue in Hub 4.3.0 which is scheduled to be released shortly.

**Comment by robpacheco** [comment]
This should be resolved as of Hub 4.3.0
