### ISSUE TITLE
Release notes 4.4.1 and read only settings

### ISSUE THREAD

**Issue by migimigi** [blackducksoftware/hub#17]
Hi, 
We using Hub with an external RDS.
We are using version 4.4.0 and began survey upgrade to version 4.4.1.
Then, we have two questions.
1.
[Release notes 4.4.1](https://github.com/blackducksoftware/hub/blob/release/4.4.1/docs/release_notes_bd_hub.pdf) 
Changes from 4.4.0 are not included.
Are there plans to be added?
2.
In Release notes 4.4.0 and 4.4.1 it is written as follows.
>Fixed Issue in 4.4.0
>The following customer-reported issues were fixed in this release:
> Docker Containers now have their root file system mounted as read only

However, the read_only setting is deleted from the docker-compose.externaldb.yml file in 4.4.1.
https://github.com/blackducksoftware/hub/commit/b42f93ad1b7c0dd563213e899e557a2b3f04a53e#diff-e6d0abdfe5a605691f0153308797e57cL5
I would be pleased if you tell me the details.

Best Regards

**Comment by robpacheco** [comment]
Thanks for adding the issue! We did remove the read-only filesystem changes from 4.4.1. The addition of read only was originally a bit pre-mature and did cause a few issues. It was also not for all orchestrations. We're looking back over better ways to achieve this across all orchestrations.

We also have updated the release notes to include changes for Hub 4.4.1. I hope I've answered your questions. If I've misunderstood, please let me know.

Thanks!

**Comment by migimigi** [comment]
Thank you!
