### ISSUE TITLE
Where are the release notes for v4.6.1?

### ISSUE THREAD

**Issue by migimigi** [blackducksoftware/hub#22]
Release notes before v4.6.0 were included in the release every time.
https://github.com/blackducksoftware/hub/tree/release/4.6.0/docs
However, it is not found in v.4.6.1.
https://github.com/blackducksoftware/hub/tree/release/4.6.1/docs/en_US

**Comment by robpacheco** [comment]
Sorry about that, we'll get this corrected! Thanks for letting us know!

**Comment by robpacheco** [comment]
Should be all set now, sorry about that.
