### ISSUE TITLE
hub containers not starting when external DB used 

### ISSUE THREAD

**Issue by prathyushmr** [blackducksoftware/hub#31]
kubectl describe pods webapp-logstash-5646f77d59-8jnqn  -n blackduck-hub1  shows 
...
 Warning  Failed     3s (x6 over 2m)   kubelet, esbdsvv53.emea.nsn-net.net  Error: configmaps "hub-db-config-granular" not found

**Comment by jangrewe** [comment]
Probably because you didn't deploy it, as mentioned in #32 .

**Comment by prathyushmr** [comment]
got it fixed . there should not be hub-db-config-granular in  	3-hub.yml  when an external db server  being used , also you should be putting HUB_POSTGRES_ENABLE_SSL: "false"  in 1-cm-hub.yml , along with the blackduck db passwords .

**Comment by jangrewe** [comment]
Sure, if you prefer to rather change 2 different files instead of just a single one...
